audit_header: false
title: "Tips with Tim"
description: Tim Peirce, a top Real Estate Agent in Hilton Head Island, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: #
  - title: Free Strategy Call
    url: https://calendly.com/tim-peirce/strategy-coaching-session
client:
  name: Tim Peirce
  title:
  license_number:
  about_markdown: |
    A committed, successful real estate professional, Tim hungered for a higher standard of excellence than the industry at large. With real estate such an essential service in our region, he grew impatient with the wide variations he saw in performance and professionalism. That inspiration is why Tim started The Peirce Group. Many team-members met Tim as a teacher; all rely on Tim as a mentor.
  market: Hilton Head Island
  brand: Tips with Tim
  brokerage: The Peirce Group
  address: 8 Lafayette Place Hilton Head Island, SC 29926
  phone: 843-481-2225
  phone_type:
  phone2:
  phone2_type:
  email: careers@thepeircegroup.com
  url: https://www.findhiltonheadareahomes.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how Tips with Tim can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Hilton Head Island Real Estate Podcast with Tim Peirce'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Hilton Head Island Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Tips with Tim - your professional Hilton Head Island Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Hilton Head Island, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Tim Peirce'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Hilton Head Island Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#ff914d'
  theme_color: '#23547b'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
